# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    visit.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', number: 'exact', descripcion: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'visit.search' } ]

    regexp.filter:
        class: 'AppBundle\Filter\RegexpFilter'
        autowire: true # See the next example for a plain old definition
        tags: [ { name: 'api_platform.filter', id: 'regexp' } ]